name: Paul Beaudoin
url: http://nonword.com

social:
  github: nonword
  twitter: nonword

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
